### ISSUE TITLE
The Pending Test Under views/sessions/ Prevents Learn From Acknowledging A Pass

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/sessions_controller_lab#10]
Learn will not give the "green light" go ahead unless the pending test is commented out. The offending test in this case is `/spec/views/sessions/new.html.erb_spec.rb`

**Comment by maxwellbenton** [comment]
Hi there @ecssiah,

I'm having difficulty reproducing the issue as there is only one spec file, `spec/controllers/session_controller_spec.rb` in this lesson, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
