### ISSUE TITLE
No need to write tests

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sessions_controller_lab#11]
The lesson says:
"Write feature tests for your views that ensure the app functions as we described in the overview."

This is not necessary; there are already tests in the lab.

Thank you.

**Comment by cdallasanta** [comment]
It is also not necessary to "Create the views that make your tests pass!" with the lab as provided.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved. Thanks for your feedback!
