### ISSUE TITLE
Remove underscores in sentences

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sessions_controller_lab#12]
Not sure why several sentences begin with underscores; I would suggest removing them and just capitalizing the word.

" _ if the user is not logged in, the page should show them a login link."
"_ if the user is logged in, the page should say, "hi, #{name}", and provide a logout link."
" _ users can enter their name in a form and click 'login'. Thereafter, the app will refer to them by that name."
" _ if the user does not enter a name, they are not logged in. Return them to the login page."

Thank you.

**Comment by heavenlyboheme** [comment]
I updated the underscores (they were placeholders for bullet points) and submitted for approval.
