### ISSUE TITLE
Duplicate Route: 'sessions/new'

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/sessions_controller_lab#2]
In routes.rb:

```
 get 'sessions/new'

  root 'application#hello'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
```

the first route `get 'sessions/new'` and the third route `get '/login' => 'sessions#new'` are the same. So students routing to login_path will get errors.

Fix:
Delete the first route `get 'sessions/new'`

**Comment by pletcher** [comment]
Thanks for reporting this! It looks like this has already been done and updated everywhere.
