### ISSUE TITLE
Session_controller.rb:18 @responce not recognized

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/sessions_controller_lab#3]
Session_controller.rb:18 reads:

```
      expect(@response.session[:name]).to eq me
```

but this raises the error:

```
Failure/Error: expect(response.session[:name]).to eq me
     NoMethodError:
       undefined method `session' for #<ActionController::TestResponse:0x007f93e2762438>
```

If we take-out '@responce' from line 18, then the implicit object being called on will be subject, which seems to be correct for this situation. If I replace @responce with 'subject' it works.

```
      expect(session[:name]).to eq me
```

**Comment by onyoo** [comment]
This seems to also apply to the following lines in the same spec:
25
30
32

**Comment by AnnJohn** [comment]
thanks @onyoo. Will look into this and update.
